### ISSUE TITLE
YeastPathways

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#16]
##### Project link
https://github.com/orgs/geneontology/projects/77

##### Project description
All pathways that have been manually curated by SGD, historically done with Pathway Tools software, are available as BioPAX files and are being imported into Noctua.  The goal is for the pathways to be editable as Noctua models, and have all YeastPathways available to users in Noctua (and therefore Alliance).

##### PI
PaulT

##### Project owner (PO)
Suzi

##### Technical lead (TL)
Dustin

##### Other personnel (OP)

Seth
SGD curators (Edith, Rob, Stacia)

##### Technical specs

no novel work, so no technical specs needed

##### Other comments

Some current work under https://github.com/geneontology/go-ontology/projects/24, should be exported.

**Comment by kltm** [comment]
@dustine32 We're trying to get things squared on the project side of things. I just wanted to check if there are any "new" technical things to deal with here? We can always talk about this on a Thursday.

**Comment by dustine32** [comment]
@kltm No new things to do for this project but there are a few lingering changes I need to implement for these tickets:
* https://github.com/geneontology/pathways2GO/issues/189 - Prepend `YeastCyc-` to model ID & filenames
* https://github.com/geneontology/pathways2GO/issues/126 - Move the full URL link back to YeastPathways (e.g., https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=NIL&object=YEAST-RIBOSYN-PWY) into a new `comment` annotation in model. This was previously in the contributor field.

I can try to knock these out probably sometime next week. There's also the `stepDirection` [ticket](https://github.com/geneontology/pathways2GO/issues/142) that I just need to confirm with Paul, Suzi is tested and Done. I updated the project board and closed some of the tickets to reflect the current state of the project.

**Comment by kltm** [comment]
Cheers, I'm finally reading this now--sorry to have made you re-explain what you've already written earlier.

**Comment by kltm** [comment]
Talking with @suzialeksander and @dustine32 about the results from the managers' meeting (tagging @pgaudet), the relative priority of this project has been increased in order to get this done "quickly".

**Comment by kltm** [comment]
From conversations with @dustine32 , I do not believe there is any novel work here are no technical doc is needed.

**Comment by kltm** [comment]
@pgaudet Updated personnel and tech.

**Comment by pgaudet** [comment]
@suzialeksander Can you add the current state of the project here please? ie remaining work and planned delivery date

Thanks, Pascale

**Comment by suzialeksander** [comment]
These models are in Noctua Dev, and SGD is testing. Hopefully, if no major issues, we can ask to have these loaded to prod quite soon (week or two?).

**Comment by pgaudet** [comment]
- SGD is testing the models on dev
- some inconsistencies between annotations between pathways and their Noctua version

**Comment by suzialeksander** [comment]
progress report:

To make this project move faster, SGD has manually checked many of the models and have decided to manually curate these, releasing them as they are ready instead of trying to perfect the code so all models are perfect upon import. The 220 YP models were loaded into Noctua prod during the 14 Sep outage, but with an oddity in the display on the Noctua homepage.  Only about 10 models had the correct load date, the others had earlier dates.  Currently waiting to hear if there are deeper issues (if models are corrupted somehow) before proceeding.  Next steps will be for SGD to correct these models and release then on a case-by-case basis.

**Comment by suzialeksander** [comment]
Listing some of the issues with importing models as-is & why we think we need to individually curate models. Discussion may be useful if other Pathways are going to be loaded into Noctua.


*One step, multiple enzymes: is apparently a ShEx violation.  Seems Noctua automatically invents a "protein-containing complex" when no such complex exists.  We floated the idea of only using Complex Portal complexes, and not allow other complexes. To fix the models now, one (fastest?) solution would be to manually add the extra proteins, and since there will be no annotations produced from the pathways (no references/EC for each step), this won't affect the intended purpose of the YP: display on Alliance pages/elsewhere that pathways would be found. 
* One enzyme, multiple steps: import (randomly?) omits some steps (all except one??)
* Adds zwitterions, unattached hydrons, orphan chemical entities, incorrect forms: NAD(1-) instead of NAD+ and NADH(2-) instead of NADH, etc.
* https://github.com/geneontology/pathways2GO/issues/258#issuecomment-1730348283
* Biopax has incorrect molecular location, which is a data issue. Some of this might be importable from existing annotations but would still likely need manual curation

**Comment by suzialeksander** [comment]
From @thomaspd:

We’d had an email exchange about this last year, and I just noticed that we haven’t yet addressed this in the conversion code. Before we do anything, I wanted to revisit the issue again, in the context of a specific example pathway that still has a couple of “molecular events” instead of molecular functions, which means we weren’t able to make a GO-CAM activity (MF) because there’s no yeast gene product doing the catalysis:

https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=PATHWAY&object=YEAST-RIBOSYN-PWY&detail-level=2

 

The pathway has an entire branch of three consecutive “molecular events” in the GO-CAM, where each one is labeled with an E.C. number in YeastPathways. None of these three reaction steps in the pathway are associated with any yeast genes. The first reaction is labeled as E.C. 1.1.1.302, which is the same E.C. as RIB7, even though SGD annotators didn’t associate it with RIB7. The second reaction has a more general E.C. (3.5.4.-) but mousing over shows a specific reaction that may not be in E.C. The third reaction is labeled with E.C. 3.1.3.104. If I look for information about this entry at:

https://enzyme.expasy.org/EC/3.1.3.104

I see that it’s annotated as being found only in bacteria and plants. So I wanted to revisit my suggestion that we should handle these “molecular events” by leaving them out of the YeastPathways, since they appear, at least in this case, to correspond to reactions that are known to happen in some organisms but have not been demonstrated in yeast. I’m wondering if Pathway Tools just makes placeholders for reactions that could potentially exist even if they are actually absent from a particular organism.

**Comment by pgaudet** [comment]
Done, as far as GO tasks is concerned.
